rules:
  imports:
    unresolved-reference:
      level: error
      except-paths:
        - data.keys
        - data.possibleLocations
        - data.users
        - data.keys.kid
        - data.users.avi.allowNoBrowser
        - data.users.avi.allowNoOrigin
  style:
    line-length:
      level: ignore
    file-length:
      level: ignore
  idiomatic:
    directory-package-mismatch:
      level: ignore
