load_module modules/ngx_otel_module.so;
load_module modules/ngx_http_js_module.so;
worker_processes  4;

error_log  /var/log/nginx/error.log warn;
pid        /tmp/nginx.pid;


events {
    worker_connections  1024;
}


http {
    otel_service_name nginx;
    otel_exporter {
        endpoint localhost:4317;
    }

    map $server_protocol $otel_network_protocol_name {
        (.+)/.+$  $1;
        default     "http";
    }

    map $server_protocol $otel_network_protocol_version {
        .+/(.+)$  $1;
        default     "1.1";
    }

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    include /etc/nginx/log_format.conf;
    
    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
