packages:
  - packages/*
  - apps/*

catalog:
  rimraf: ^6.1.2
  typescript: ^5.9.3
  eslint: ^9.39.2
  '@map-colonies/eslint-config': '^8.0.0'
  '@map-colonies/tsconfig': ^2.0.0
  '@map-colonies/js-logger': ^4.1.0
  '@map-colonies/openapi-helpers': '5.1.0'
  'vitest': '4.0.18'
  '@vitest/coverage-v8': '4.0.18'
  '@vitest/ui': '4.0.18'
  '@types/node': '24.12.0'
