packages:
  - packages/*
  - apps/*

catalog:
  rimraf: ^6.1.2
  typescript: ^5.9.3
  eslint: ^9.39.2
  '@map-colonies/eslint-config': '^8.0.0'
  '@map-colonies/tsconfig': ^2.0.0
  '@map-colonies/js-logger': ^4.1.0
