{{- $releaseName := .Release.Name -}}
{{- $chartName := include "auth-ui.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "auth-ui.environment" . }}
    release: {{ $releaseName }}
    {{- include "auth-ui.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "auth-ui.selectorLabels" . | nindent 4 }}
{{- end }}
