{{- $chartName := include "opa-la.name" . -}}
{{- if or (index .Values "auth-ui" "enabled") (index .Values "kiosk-ui" "enabled") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-la-configmap
data:
  config.json: {{ index .Values "auth-ui" "config" | quote }}
  extension.conf: |
      root   /usr/share/nginx/html;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;
{{- end }}
