{{- $releaseName := .Release.Name -}}
{{- $chartName := include "opa-la.name" . -}}
{{- if (not (.Values.dbConfig.useExternalSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-postgres-secret
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "opa-la.environment" . }}
    release: {{ $releaseName }}
    {{- include "opa-la.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.dbConfig.username | b64enc }}
  password: {{ .Values.dbConfig.password | b64enc }}
{{- end }}
