openapi: 3.0.1
servers:
  - url: /
  - url: /api
info:
  title: Token Kiosk Service
  description: OAuth2/OpenID Connect authentication service for handling user authentication flows
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /token:
    get:
      operationId: getToken
      summary: generated and returns a temporary access token for the MapColonies services.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /auth/me:
    get:
      operationId: getCurrentUser
      tags:
        - authentication
      summary: Get current authenticated user information
      description: Returns information about the currently authenticated user
      security:
        - bearerAuth: []
      responses:
        200:
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userInfo'
        401:
          description: Unauthorized - No valid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
security:
  - {}
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer token authentication using JWT access tokens
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    tokenResponse:
      type: object
      required:
        - token
        - expiration
        - domains
      properties:
        token:
          type: string
          description: Temporary access token for MapColonies services
        expiration:
          type: string
          format: date-time
          description: Expiration date and time of the token
        domains:
          type: array
          items:
            type: string
          description: List of domains the token is valid for
    userInfo:
      type: object
      required:
        - sub
      properties:
        sub:
          type: string
          description: Unique user identifier (subject)
        name:
          type: string
          description: User display name
        given_name:
          type: string
          description: User first name
        family_name:
          type: string
          description: User last name
        middle_name:
          type: string
          description: User middle name
        nickname:
          type: string
          description: User nickname
        preferred_username:
          type: string
          description: User preferred username
        email:
          type: string
          format: email
          description: User email address
        gender:
          type: string
          description: User gender
        phone_number:
          type: string
          description: User phone number
