openapi: 3.0.1
servers:
  - url: /
  - url: /api
info:
  title: Token Kiosk Service
  description: OAuth2/OpenID Connect authentication service for handling user authentication flows
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /token:
    get:
      operationId: getToken
      summary: generated and returns a temporary access token for the MapColonies services.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tokenResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        401:
          description: Unauthorized - No valid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        403:
          description: Forbidden - User is banned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /auth/me:
    get:
      operationId: getCurrentUser
      tags:
        - authentication
      summary: Get current authenticated user information
      description: Returns information about the currently authenticated user
      security:
        - openid: []
      responses:
        200:
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userInfo'
        401:
          description: Unauthorized - No valid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /guides:
    get:
      operationId: getGuides
      summary: Get available documentation guides
      description: Returns a list of guides to documentation and resources related to the Token Kiosk service
      security:
        - openid: []
      responses:
        200:
          description: Guides retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/guidesResponse'
        401:
          description: Unauthorized - No valid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        403:
          description: Forbidden - User is banned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /files/{type}:
    get:
      operationId: getFile
      summary: Get QLR for QGIS or lyrx for ArcGIS Pro
      description: Returns a File that can be used to load specific MapColonies layers already configured and ready to use in QGIS or ArcGIS Pro.
      security:
        - openid: []
      parameters:
        - name: type
          in: path
          required: true
          description: Type of file to retrieve (qlr for QGIS, lyrx for ArcGIS Pro)
          schema:
            $ref: '#/components/schemas/fileTypes'
      responses:
        200:
          description: QLR file retrieved successfully
          headers:
            Content-Disposition:
              description: Indicates that the content is a file attachment
              schema:
                type: string
                example: attachment; filename="token-kiosk.qlr"
          content:
            application/xml:
              schema:
                type: string
            application/json:
              schema:
                type: string
        401:
          description: Unauthorized - No valid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        403:
          description: Forbidden - User is banned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
security:
  - {}
  - openid: []
components:
  securitySchemes:
    openid:
      type: openIdConnect
      openIdConnectUrl: http://localhost:8080/realms/my-local-app/.well-known/openid-configuration

  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    tokenResponse:
      type: object
      required:
        - token
        - expiration
      properties:
        token:
          type: string
          description: Temporary access token for MapColonies services
        expiration:
          type: string
          format: date-time
          description: Expiration date and time of the token
    userInfo:
      type: object
      required:
        - sub
      properties:
        sub:
          type: string
          description: Unique user identifier (subject)
        name:
          type: string
          description: User display name
        given_name:
          type: string
          description: User first name
        family_name:
          type: string
          description: User last name
        middle_name:
          type: string
          description: User middle name
        nickname:
          type: string
          description: User nickname
        preferred_username:
          type: string
          description: User preferred username
        email:
          type: string
          format: email
          description: User email address
        gender:
          type: string
          description: User gender
        phone_number:
          type: string
          description: User phone number
    guidesResponse:
      required:
        - qgis
        - arcgis
      type: object
      properties:
        qgis:
          type: string
          description: Link to QGIS documentation
        arcgis:
          type: string
          description: Link to ArcGIS Pro documentation
    fileTypes:
      type: string
      enum: [qlr, lyrx]
      description: Type of file to retrieve (qlr for QGIS, lyrx for ArcGIS Pro)
