{{- $chartName := include "auth-manager.name" . -}}
{{- $tracingUrl := include "auth-manager.tracingUrl" . -}}
{{- $metricsUrl := include "auth-manager.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{- with .Values.dbConfig }}
  DB_HOST: {{ .host }}
  DB_NAME: {{ .database }}
  DB_PORT: {{ .port | default 5432 | quote }}
  {{- end -}}
  {{- if .Values.dbConfig.sslAuth.enabled }}
  DB_ENABLE_SSL_AUTH: "true"
  {{- else }}
  DB_ENABLE_SSL_AUTH: "false"
  {{- end }}
  {{- with .Values.env.configManager }}
  CONFIG_OFFLINE_MODE: {{ .offlineMode | quote }}
  {{- if not .offlineMode }}
  CONFIG_SERVER_URL: {{ .serverUrl | quote }}
  CONFIG_NAME: {{ .configName | quote }}
  {{- end }}
  {{- end }}
{{- end }}
