{{- $releaseName := .Release.Name -}}
{{- $chartName := include "auth-manager.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    {{- include "auth-manager.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "auth-manager.selectorLabels" . | nindent 4 }}
{{- end }}
