{{- $releaseName := .Release.Name -}}
{{- $chartName := include "auth-manager.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "auth-manager.labels" . | nindent 4 }}
    {{ include "common-labels-and-annotations.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "common-labels-and-annotations.serviceAnnotations" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "auth-manager.selectorLabels" . | nindent 4 }}
{{- end }}
