{{- $releaseName := .Release.Name -}}
{{- $chartName := include "token-kiosk.name" . -}}
{{- $cloudProviderFlavor := include "token-kiosk.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "token-kiosk.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "token-kiosk.cloudProviderImagePullSecretName" . -}}
{{- $imageTag := include "token-kiosk.tag" . -}}
{{ $postgresSecretName := ternary .Values.dbConfig.secretName (printf "%s%s" .Release.Name "-postgres-secret") .Values.dbConfig.useExternalSecret }}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" (include "token-kiosk.fullname" .) }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "token-kiosk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "token-kiosk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "token-kiosk.labels" . | nindent 8 }}
      annotations:
        {{ include "mc-labels-and-annotations.annotations" . | nindent 8 }}
        {{- if .Values.resetOnConfigChange }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
          {{- end }}
          {{- if .Values.command }}
          command: 
          {{- toYaml .Values.command | nindent 12 }}
          {{- if .Values.args }}
          args: 
          {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.ca.enabled }}
            - mountPath: {{ printf "%s/%s" .Values.ca.path .Values.ca.key | quote }}
              name: root-ca
              subPath: {{ quote .Values.ca.key }}
            {{- end }}
            {{- if .Values.dbConfig.sslAuth.enabled }}
            - name: ca-file
              mountPath: /tmp/certs/{{ .Values.dbConfig.sslAuth.caFileName }}
              subPath: {{ .Values.dbConfig.sslAuth.caFileName }}
            - name: key-file
              mountPath: /tmp/certs/{{ .Values.dbConfig.sslAuth.keyFileName }}
              subPath: {{ .Values.dbConfig.sslAuth.keyFileName }}
            - name: cert-file
              mountPath: /tmp/certs/{{ .Values.dbConfig.sslAuth.certFileName }}
              subPath: {{ .Values.dbConfig.sslAuth.certFileName }}
            {{- end }}
            {{- if .Values.extraVolumeMounts -}}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            {{- if .Values.configManager.offlineMode }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresSecretName }}
                  key: username
            {{- if not .Values.dbConfig.sslAuth.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresSecretName }}
                  key: password
            {{- end }}
            {{- end }}
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            {{- if .Values.ca.enabled }}
            - name: REQUESTS_CA_BUNDLE
              value: {{ printf "%s/%s" .Values.ca.path .Values.ca.key | quote }}
            - name: NODE_EXTRA_CA_CERTS
              value: {{ printf "%s/%s" .Values.ca.path .Values.ca.key }}
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}            
          envFrom:
            - configMapRef:
                name: {{ printf "%s-configmap" (include "token-kiosk.fullname" .) }}
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.env.targetPort }}
          {{- end }}        
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
        {{- if .Values.sidecars }}
        {{ tpl (toYaml .Values.sidecars) . | nindent 8 }}
        {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: 'nginx-extra-configmap'      
        {{- if .Values.ca.enabled }}
        - name: root-ca
          secret:
            secretName: {{ .Values.ca.secretName }}
        {{- end }}
        {{- if .Values.dbConfig.sslAuth.enabled }}
        - name: ca-file
          secret:
            secretName: {{ $postgresSecretName }}
            items:
              - key: {{ .Values.dbConfig.sslAuth.caFileName }}
                path: ca.crt
        - name: key-file
          secret:
            secretName: {{ $postgresSecretName }}
            items:
              - key: {{ .Values.dbConfig.sslAuth.keyFileName }}
                path: key.pem
        - name: cert-file
          secret:
            secretName: {{ $postgresSecretName }}
            items:
              - key: {{ .Values.dbConfig.sslAuth.certFileName }}
                path: cert.pem
        {{- end }}
        {{- if .Values.extraVolumes -}}
          {{ tpl (toYaml .Values.extraVolumes) . | nindent 8 }}
        {{- end }}    
{{- end -}}
