#!/bin/bash
# Generated by Copilot
# Script to create auth-manager database in PostgreSQL container

set -e
set -u

echo "Creating database 'auth-manager'"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "auth-manager";
    GRANT ALL PRIVILEGES ON DATABASE "auth-manager" TO "$POSTGRES_USER";
    CREATE DATABASE "keycloak";
    GRANT ALL PRIVILEGES ON DATABASE "keycloak" TO "$POSTGRES_USER";
EOSQL

echo "Creating schema 'auth_manager' in database 'auth-manager'"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "auth-manager" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS auth_manager;
    GRANT ALL ON SCHEMA auth_manager TO "$POSTGRES_USER";
EOSQL
echo "Database 'auth-manager' and schema 'auth_manager' created successfully"
