services:
  devcontainer:
    environment:
      - DB_NAME=auth-manager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace:cached
    command: sleep infinity
    network_mode: 'service:postgres'
    depends_on:
      - postgres
      - minio
      - keycloak

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 9090
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_LOGIN_BANNER: '"Development Environment - No Authentication Required"'
    volumes:
      - ./data/pgadmin-servers.json:/pgadmin4/servers.json
      - ./data/pgadmin-passfile:/pgadmin4/passfile:ro
    depends_on:
      - postgres
    network_mode: 'service:postgres'

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - minio_data:/data
    network_mode: 'service:postgres'
    depends_on:
      - postgres

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set minio http://localhost:9000 minioadmin minioadmin;
      mc mb minio/opa --ignore-existing;
      echo 'MinIO bucket created successfully';
      "
    network_mode: 'service:postgres'

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9999
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HTTP_PORT: 9999
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./data/keycloak-realm.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres
    network_mode: 'service:postgres'

volumes:
  postgres_data:
  minio_data:

networks:
  dev-network:
    driver: bridge
