{{- $chartName := include "opa.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  OPA_CONFIG: {{ tpl (.Files.Get "config/opa.yaml") . | quote }}
{{- end }}
