{{- $releaseName := .Release.Name -}}
{{- $chartName := include "opa.name" . -}}
{{- $cloudProviderFlavor := include "opa.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "opa.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "opa.cloudProviderImagePullSecretName" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "opa.environment" . }}
    release: {{ $releaseName }}
    {{- include "opa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "opa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "opa.selectorLabels" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      volumes:
        - name: opa-configfile
          configMap:
            name: {{ .Release.Name }}-{{ $chartName }}-configmap
            items:
            - key: "OPA_CONFIG"
              path: "opa.yaml"
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ .tag }}
          {{- end }}
          volumeMounts:
          - name: opa-configfile
            mountPath: /opa/opa.yaml
            readOnly: true
            subPath: opa.yaml
          args:
          - "run"
          - "--server"
          - "--addr=0.0.0.0:{{ .Values.targetPort }}"
          - "--diagnostic-addr=0.0.0.0:{{ .Values.diagnosticTargetPort }}"
          - "--config-file"
          - "/opa/opa.yaml"
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health?plugins
              port: {{ .Values.diagnosticTargetPort }}
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health?plugins
              port: {{ .Values.diagnosticTargetPort }}
            initialDelaySeconds: 5
            periodSeconds: 30          
{{- end -}}
