apiVersion: v2
name: opa
description: A Helm chart for opa
type: application
version: 1.12.0
appVersion: 1.0.1
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
  - name: fluent-bit
    repository: oci://ghcr.io/fluent/helm-charts/fluent-bit
    version: 0.56.0
    condition: fluent-bit.enabled
