apiVersion: v2
name: opa-la
description: A Helm chart for opa-la
type: application
version: 1.2.0
dependencies:
  - name: 'opa'
    repository: file://charts/opa
    condition: opa.enabled
  - name: 'auth-cron'
    repository: file://../packages/auth-cron/helm
    condition: auth-cron.enabled
  - name: 'auth-manager'
    repository: file://../packages/auth-manager/helm
    condition: auth-manager.enabled
