apiVersion: v2
name: opa-la
description: A Helm chart for opa-la
type: application
version: 1.4.0
dependencies:
  - name: opa
    repository: file://charts/opa
    condition: opa.enabled
    version: 1.3.0
  - name: auth-cron
    repository: file://../packages/auth-cron/helm
    version: 1.3.0
    condition: auth-cron.enabled
  - name: auth-manager
    repository: file://../packages/auth-manager/helm
    version: 1.3.0
    condition: auth-manager.enabled
  - name: auth-ui
    repository: file://../packages/auth-ui/helm
    version: 1.3.0
    condition: auth-ui.enabled
