apiVersion: v2
name: opa-la
description: A Helm chart for opa-la
type: application
version: 1.12.0 # x-release-please-version
dependencies:
  - name: opa
    repository: file://charts/opa
    condition: opa.enabled
    version: 1.12.0 # x-release-please-version
  - name: auth-cron
    repository: file://../apps/auth-cron/helm
    condition: auth-cron.enabled
    version: 1.12.0 # x-release-please-version
  - name: auth-manager
    repository: file://../apps/auth-manager/helm
    condition: auth-manager.enabled
    version: 1.12.0 # x-release-please-version
  - name: nginx
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
    condition: auth-ui.enabled
    alias: auth-ui
    version: 2.1.6
  - name: token-kiosk
    repository: file://../apps/token-kiosk/helm
    condition: token-kiosk.enabled
    version: 1.12.0 # x-release-please-version
  - name: nginx
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
    condition: kiosk-ui.enabled
    alias: kiosk-ui
    version: 2.1.6
  - name: grafana-datasources
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    condition: grafana-datasources.enabled
    version: 1.0.0
