{{- $chartName := include "auth-cron.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  CONFIG_OFFLINE_MODE: {{ .Values.env.configManager.offlineMode | quote }}
  {{- if .Values.env.configManager.offlineMode }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  DB_HOST: {{ .Values.dbConfig.host }}
  DB_NAME: {{ .Values.dbConfig.database }}
  DB_PORT: {{ .Values.dbConfig.port | default 5432 | quote }}
  DB_ENABLE_SSL_AUTH: {{ .Values.dbConfig.sslAuth.enabled | quote }}
  {{- if .Values.dbConfig.sslAuth.enabled }}
  DB_CERT_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.caFileName }}
  {{- end }}
  {{- else }}
  CONFIG_SERVER_URL: {{ .Values.env.configManager.serverUrl | quote }}
  CONFIG_NAME: {{ .Values.env.configManager.configName | quote }}
  {{- end }}
{{- end }}
