{{- $chartName := include "auth-cron.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{- with .Values.dbConfig }}
  DB_HOST: {{ .host }}
  DB_NAME: {{ .database }}
  DB_PORT: {{ .port | default 5432 | quote }}
  {{- end -}}
  {{- if .Values.dbConfig.sslAuth.enabled }}
  DB_ENABLE_SSL_AUTH: "true"
  DB_CERT_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.caFileName }}
  {{- else }}
  DB_ENABLE_SSL_AUTH: "false"
  {{- end }}
  {{- with .Values.env.configManager }}
  CONFIG_OFFLINE_MODE: {{ .offlineMode | quote }}
  {{- if not .offlineMode }}
  CONFIG_SERVER_URL: {{ .serverUrl | quote }}
  CONFIG_NAME: {{ .configName | quote }}
  {{- end }}
  {{- end }}
{{- end }}
