{{- $releaseName := .Release.Name -}}
{{- $chartName := include "auth-cron.name" . -}}
{{- if and .Values.enabled .Values.env.configManager.offlineMode -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-cron-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}share
    component: {{ $chartName }}
    environment: {{ include "auth-cron.environment" . }}
    release: {{ $releaseName }}
    {{- include "auth-cron.labels" . | nindent 4 }}
type: Opaque
data:
  config: {{ printf "{ \"cron\": %s }" (mustToJson .Values.cronConfig) | b64enc }}
{{- end }}
