{{- $releaseName := .Release.Name -}}
{{- $chartName := include "auth-cron.name" . -}}
{{- $cloudProviderFlavor := include "auth-cron.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "auth-cron.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "auth-cron.cloudProviderImagePullSecretName" . -}}
{{ $postgresSecretName := ternary .Values.dbConfig.externalSecretName (printf "%s%s" .Release.Name "-postgres-secret") .Values.dbConfig.useExternalSecret }}
{{- $imageTag := include "auth-cron.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "auth-cron.environment" . }}
    release: {{ $releaseName }}
    {{- include "auth-cron.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "auth-cron.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "auth-cron.selectorLabels" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          volumeMounts:
            {{- if .Values.caSecretName }}
            - mountPath: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
              name: root-ca
              subPath: {{ quote .Values.caKey }}
            {{- end }}
            {{- if .Values.env.configManager.offlineMode }}
            - name: config
              mountPath: /usr/src/app/packages/auth-cron/config/production.json
              subPath: production.json
              readOnly: true
            {{- end }}
            {{- if .Values.dbConfig.sslAuth.enabled }}
            {{- if .Values.dbConfig.sslAuth.caFileName }}
            - name: ca-file
              mountPath: /tmp/certs/{{ .Values.dbConfig.sslAuth.caFileName }}
              subPath: {{ .Values.dbConfig.sslAuth.caFileName }}
            {{- end }}
            {{- if .Values.dbConfig.sslAuth.keyFileName }}
            - name: key-file
              mountPath: /tmp/certs/{{ .Values.dbConfig.sslAuth.keyFileName }}
              subPath: {{ .Values.dbConfig.sslAuth.keyFileName }}
            {{- end }}
            {{- if .Values.dbConfig.sslAuth.certFileName }}
            - name: cert-file
              mountPath: /tmp/certs/{{ .Values.dbConfig.sslAuth.certFileName }}
              subPath: {{ .Values.dbConfig.sslAuth.certFileName }}
            {{- end }}
            {{- end }}
          env:
            {{- if .Values.env.configManager.offlineMode }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresSecretName }}
                  key: username
            {{- if not .Values.dbConfig.sslAuth.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresSecretName }}
                  key: password
            {{- end }}
            {{- end }}
            {{- if .Values.caSecretName }}
            - name: REQUESTS_CA_BUNDLE
              value: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
            - name: NODE_EXTRA_CA_CERTS
              value: {{ printf "%s/%s" .Values.caPath .Values.caKey | quote }}
            {{- end }}
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: 8080
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.caSecretName }}
        - name: root-ca
          secret:
            secretName: {{ .Values.caSecretName }}
        {{- end }}
        {{- if .Values.dbConfig.sslAuth.enabled }}
        {{- if .Values.dbConfig.sslAuth.caFileName }}
        - name: ca-file
          secret:
            secretName: {{ $postgresSecretName }}
            items:
              - key: {{ .Values.dbConfig.sslAuth.caFileName }}
                path: ca.crt
        {{- end }}
        {{- if .Values.dbConfig.sslAuth.keyFileName }}
        - name: key-file
          secret:
            secretName: {{ $postgresSecretName }}
            items:
              - key: {{ .Values.dbConfig.sslAuth.keyFileName }}
                path: key.pem
        {{- end }}
        {{- if .Values.dbConfig.sslAuth.certFileName }}
        - name: cert-file
          secret:
            secretName: {{ $postgresSecretName }}
            items:
              - key: {{ .Values.dbConfig.sslAuth.certFileName }}
                path: cert.pem
        {{- end }}
        {{- end }}
        {{- if .Values.env.configManager.offlineMode }}
        - name: config
          secret:
            secretName: {{ $releaseName }}-{{ $chartName }}-cron-secret
            items:
            - key: config
              path: production.json
        {{- end }}
{{- end -}}
