services:
  s3:
    url: {{ .Values.s3.endpoint }}
    credentials:
      s3_signing:
        # Required for finding the envs for S3
        environment_credentials: {}
{{- if .Values.fluent-bit.enabled}}
  fluent-bit:
    enabled: {{ .Values.fluentBit.enabled }}
    config:
      inputs:
        - name: tail
          parameters:
{{- end }}
bundles:
  authz:
    service: s3
    resource: {{ .Values.s3.filePath }}
{{- if .Values.s3.useAwsS3 }}
    # Persist bundle to disk for AWS S3
    persist: true
{{- end }}

status:
  console: {{ .Values.status.console }}
  prometheus: true

decision_logs:
  console: {{ .Values.decisionLogs.console }}
  {{- if .Values.fluent-bit.enabled }}
  service: fluent-bit
  {{- end }}
  reporting:
    buffer_size_limit_bytes: {{ .Values.decisionLogs.maxBufferSize }}
    min_delay_seconds: {{ .Values.decisionLogs.minDelaySeconds }}
    max_delay_seconds: {{ .Values.decisionLogs.maxDelaySeconds }}

{{ if .Values.tracing.enabled }}
distributed_tracing:
  type: {{ .Values.tracing.type }}
  address: {{ .Values.tracing.endpoint }}
  sample_percentage: {{ .Values.tracing.samplePercentage | default 100 }}
{{ end }}

persistence_directory: {{ .Values.bundlePersistencePath }}

storage:
  disk:
    auto_create: true
    directory: {{ .Values.bundlePersistencePath }}


labels:
  {{- range $key, $value := .Values.labels }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
